### ISSUE TITLE
KeyError: 'IOTEDGE_IOTHUBHOSTNAME'

### ISSUE THREAD

**Issue by naseef** [lucadruda/aziotedge-idtranslation-sample#1]
Could you please show me some light on the below error   when in run this in simulator
```
File "/app/server/multiclient.py", line 60, in register_client
    c_str = 'HostName={};DeviceId={};SharedAccessKey={}'.format(environ['IOTEDGE_IOTHUBHOSTNAME'], client_id, client_key)
  File "/usr/local/lib/python3.7/os.py", line 681, in __getitem__
    raise KeyError(key) from None
KeyError: 'IOTEDGE_IOTHUBHOSTNAME'
```

**Comment by lucadruda** [comment]
Hi, this sample does not work on local simulator. I'll add info to the README.
Also I will merge latest bits on master so I suggest you to wait for this to have a more usable solution.
